DWH_Project:
  outputs:
    dev:
      account: IYKQGXO-ACB05409
      database: NETFILXDB
      password: IndiaGanga@999
      role: ACCOUNTADMIN
      schema: NETFILXSCHEMA
      threads: 3
      type: snowflake
      user: GOURC
      warehouse: COMPUTE_WH
  target: dev
